Модуль 3, задачи 1-5
js-tasks-ru/jsbasic-20211108_nov-anna pull request #9
Opened 2021-11-21 18:04 UTC by AnnaElis

2021-11-21 18:05 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-22 09:25 UTC, SinimaWath requested changes

2021-11-22 09:25 UTC, SinimaWath commented on 3-module/1-task/index.js
> +return newNames;
нет необходимости в временном массиве. Функция, которая передается в map, должна возвращать новое значение. Оно и добавиться в массив.

Правильно вот так:
`users.map((item) => item.name)`

2021-11-22 09:25 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  });
Давай попробуем переписать, на filter->map->join('\n')

2021-11-28 10:31 UTC, SinimaWath commented
Давай поправим замечания, и пойдем дальше на другие домашки

2021-11-29 17:30 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-30 12:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-11-30 12:52 UTC, closed without merging